# Generated by Django 3.2.7 on 2022-03-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Картинка продукта', 'verbose_name_plural': 'Картинки продуктов'},
        ),
    ]
