# Generated by Django 3.2.7 on 2022-04-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
