# Generated by Django 3.2.7 on 2022-04-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productcomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_product_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_product_image'),
        ),
    ]
