# Generated by Django 3.2.7 on 2022-04-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_favoriteproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproduct',
            name='product',
            field=models.ManyToManyField(related_name='favorite_product', to='products.Product'),
        ),
    ]
