# Generated by Django 3.2.7 on 2022-03-31 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('signature', models.ImageField(upload_to='signature/')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_image/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.about')),
            ],
        ),
    ]
