# Generated by Django 3.2.7 on 2022-03-31 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_about_aboutimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutimage',
            options={'verbose_name': 'Фото о нас', 'verbose_name_plural': 'Фото о нас'},
        ),
    ]
